config/routes.rb
Rails.application.routes.draw do

  resources :courses, :except => [:show]  do
    member do
      get :summary
    end
    resources :exams, :except => [:show] do
      member do
        get :results
        post :results, to: "exams#change_results"
      end
    end
    resources :students, :except => [:show]
  end

  devise_for :users
  
  root :to => "courses#index"
  
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :results, :dependent => :restrict_with_error
  belongs_to :course

  # we use reject if all_blank because if a blank score is submitted,
  # is it a new record that is invalid (blank name) and should cause the save to fail
  # but we wanna ignore that
  accepts_nested_attributes_for :results

  validates_presence_of :title, :date, :passing_score

  validates :title, :uniqueness => {:scope => [:course_id]}

  validates :passing_score, 
    inclusion: { in: 0..100 ,message: "should be a number between 0 and 100, representing a proportion"}

  validate :correct_year

  def find_total_attended
    (Result.find_total_for self).size() 
  end

  def find_passing
    (Result.find_passing_for self).size() 
  end

  def correct_year
    possible_years = course.year..(course.year + 1)
    errors.add(:date, "'s year should be #{course.year} or #{course.year + 1} ") unless date.present? && (possible_years.include? date.year)
  end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exams
  before_action :set_exam, only: [:show, :edit, :update, :destroy, :results, :change_results]

  def results
    if @exam.course.students.empty?
      redirect_to course_exams_url(@course), alert: 'The course where this exam belongs to has no students so you cannot upload results.' 
    else
      @exam.course.students.each do |std|
        @exam.results.find_or_initialize_by(student: std)
      end
    end
  end

  def change_results
    if @exam.update(results_params)
      redirect_to(results_course_exam_url(@exam.course, @exam), notice: 'Scores updated')
    else
      render action: 'results'
    end
  end

  # GET courses/1/exams
  def index
    @exams = @course.exams.order(:date)
  end

  # GET courses/1/exams/new
  def new
    @exam = @course.exams.build
  end

  # GET courses/1/exams/1/edit
  def edit
  end

  # POST courses/1/exams
  def create
    @exam = @course.exams.build(exam_params)

    if @exam.save
      redirect_to( course_exams_url(@exam.course), notice: 'Exam was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT courses/1/exams/1
  def update
    if @exam.update_attributes(exam_params)
      redirect_to( course_exams_url(@exam.course), notice: 'Exam was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE courses/1/exams/1
  def destroy
    @exam.destroy
    if (!@exam.results.empty?)
      respond_to do |format|
        format.html { redirect_to course_exams_url(@course), alert: 'Exam was not destroyed due to the fact it has results related.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to course_exams_url(@course), notice: 'Exam was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exams
      @course = Course.find(params[:course_id])
    end

    def set_exam
      @exam = @course.exams.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def exam_params
      params.require(:exam).permit(:title, :passing_score, :date)
    end

    def results_params
      params.require(:exam).permit(results_attributes: [:id, :score, :student_id])
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_for([@exam.course, @exam]) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h6>Oops! <%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h6>

      <ul>
      <% @exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title ,class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :passing_score %> (proportion over 100) <br />
    <%= f.number_field :passing_score, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: 'btn btn-outline-warning'%>
    <%= link_to 'Back',  course_exams_path(@exam.course), class: 'btn btn-outline-dark' %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<div class="container col-md-4 col-md-offset-4" style="width:400px">

  <div class="card" style="width:400px">
    <%=image_tag("course1.jpeg", alt: "Card image, exam", class: "card-img-top")%>
    <div class="card-body">
      <h4 class="card-title">Editing Exam</h4>
      <p class="card-text">
        <%= render 'form' %>
      </p>
    </div>
  </div>

</div>

app/views/exams/index.html.erb
<div class="container col-md-8 col-md-offset-2 ">
  <h1>Listing <%= @course.year %> Exams</h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Passing score</th>
        <th>Date</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @exams.each do |exam| %>
        <tr>
        <td><%= exam.title %></td>
        <td><%= exam.passing_score %> %</td>
        <td><%= exam.date %></td>
        <td>
          <%= link_to 'Edit', edit_course_exam_path(exam.course, exam), class: 'btn btn-outline-success' %>
          <%= link_to 'Destroy', [exam.course, exam],  data: { confirm: 'Are you sure?' }, :method => :delete, class: 'btn btn-outline-danger' %>
          <a class="btn btn-outline-secondary" href="<%=  results_course_exam_url(exam.course, exam) %>">
              Results
          </a>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Exam', new_course_exam_path(params[:course_id]), class: 'btn btn-outline-warning' %>
  <%= link_to 'Back to Courses', courses_path, class: 'btn btn-outline-dark' %>
</div>

app/views/exams/new.html.erb
<div class="container col-md-4 col-md-offset-4" style="width:400px">

  <div class="card" style="width:400px">
    <%=image_tag("course1.jpeg", alt: "Card image, exam", class: "card-img-top")%>
    <div class="card-body">
      <h4 class="card-title">New Exam</h4>
      <p class="card-text">
        <%= render 'form' %>
      </p>
    </div>
  </div>

</div>

app/views/exams/results.html.erb
<div class="container col-md-8 col-md-offset-2 ">
    <h1>Listing Grades for <%= @exam.title %> </h1>
    <%= form_for([@exam.course, @exam], url: results_course_exam_path(@exam.course, @exam), method: :post) do |f| %>
        <% if @exam.errors.any? %>
        <div id="error_explanation">
            <h6>Oops! <%= pluralize(@exam.errors.count, "error") %> prohibited this result from being saved:</h6>
            <ul>
            <% @exam.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
        <% end %>

        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th>Student</th>
                <th>Score (proportion over 100)</th>
            </tr>
            </thead>
            <tbody>
            <%= f.fields_for :results do |a|%>
                <tr>
                <td> <%= a.object.student %> </td>
                <td>
                    <div class="field">
                        <%= a.number_field :score, class: 'form-control', style: 'width: 186px;'%>
                        <%= a.hidden_field :id %>
                        <%= a.hidden_field :student_id %>
                    </div>
                </td>
                </tr>
            <% end %>
            </tbody>
        </table>
    
        <br>
        <div class="actions">
        <%= f.submit class: 'btn btn-outline-warning' %>
        <%= link_to 'Back', course_exams_path(@exam.course) , class: 'btn btn-outline-dark'%>
        </div>
    <% end %>
</div>
    